# Generated by Django 5.2.5 on 2025-08-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='price_gross_eur_cents',
            new_name='price_gross_cents',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='sku',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, help_text="Optional: tie this image to a color (e.g. 'Black'). Leave blank for generic images.", max_length=40),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
