# Generated by Django 5.2.5 on 2025-08-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_gross_eur_cents_variant_price_gross_cents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('percent_off', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_off_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('min_subtotal_cents', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
